#!/usr/bin/env bash

export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"

function cleanup {
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -P $$ 2>/dev/null
}

trap cleanup EXIT 2>/dev/null

# this should work with both local and global ueberzug install
if [ ! -x $(command -v ueberzug >/dev/null 2>&1) ]; then
	vifm
	exit
fi

mkfifo "$FIFO_UEBERZUG"
tail -f "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &
vifm "$@"
