#!/bin/zsh
# vim: ft=sh

# Print volumes
if [[ "$#" == "0" ]]; then
  speaker_vol=$(amixer -c 0 sget Speaker | awk '/Front Left:/{ print $5 }' | tr -d '[]')
  headphones_vol=$(amixer -c 0 sget Headphone | awk '/Front Left:/{ print $5 }' | tr -d '[]')
  echo '📢 '$speaker_vol' 🎧 '$headphones_vol
fi
