#!/bin/zsh

if [[ "$#" == "0" ]]; then
  echo -n '<span font="FontAwesome5ProSolid">&#xf042;</span> '
  printf '%.3d' $(xbacklight)
  exit 0
fi

case "$1" in
  brighter)
    shift
    xbacklight -inc 5
    pkill --signal SIGRTMIN+10 i3blocks
    ;;
  darker)
    shift
    xbacklight -dec 5
    pkill --signal SIGRTMIN+10 i3blocks
    ;;
  reset)
    shift
    xbacklight -set 100
    pkill --signal SIGRTMIN+10 i3blocks
    ;;
esac
