#!/usr/bin/env sh

if [ "$button" -eq 1 ]; then

  # TODO: Imput volume per dialogue
  yad --scale
fi

if [ "$#" -eq 0 ]; then
  echo -n '<span font="FontAwesome5ProSolid">&#xf042;</span> '
  echo $(printf '%.3d' $(xbacklight))
  exit 0
fi

case "$1" in
  brighter)
    xbacklight -inc 5
    ;;
  darker)
    xbacklight -dec 5
    ;;
  reset)
    xbacklight -set 100
    ;;
esac
pkill --signal SIGRTMIN+10 i3blocks # refresh
