#!/usr/bin/env sh

symbol='<span font="FontAwesome">&#xf042;</span>'
current_backlight=$(light)

if [ "$button" -eq 1 ]; then

  new_backlight=$( yad                      \
    --scale                                 \
    --vertical                              \
    --value="$current_backlight"            \
    --height="255"                          \
    --width="60"                            \
    --min-value="1"                         \
    --max-value="100"                       \
    --text="$symbol Choose a new backlight" \
    --mouse )
  if [ "$?" -eq 0 ]; then
    light -S $new_backlight
    pkill --signal SIGRTMIN+10 i3blocks
  fi
fi

if [ "$#" -eq 0 ]; then
  echo "$symbol" $(printf '%.3d' $current_backlight)
  exit 0
fi

case "$1" in
  brighter)
    light -A 5
    ;;
  darker)
    light -U 5
    ;;
  reset)
    light -S 100
    ;;
esac
pkill --signal SIGRTMIN+10 i3blocks # refresh
