#!/usr/bin/env sh

# TODO: Implement a default action which leaves the layout as it is.
#       Read monitor positions from xrandr and set them via xrandr --output

numOfMonitors=$(xrandr --listactivemonitors | head -n 1 | awk '{ print $2 }')

if [ "$numOfMonitors" -eq 2 ]; then
  # Get monitors' names
  monitors=$(xrandr --listactivemonitors | tail -n 2 | awk '{ print $4 }')
  m1=$(echo "$monitors" | head -n 1)
  m2=$(echo "$monitors" | tail -n 1)

  # LMouse: Primary to the left; to the right otherwise.
  if [ "$button" -eq 1 ]; then
    xrandr --output $m1 --left-of $m2
    echo -n '<span font="FontAwesome5ProSolid">&#xf108;</span> '
    echo '<span font="FontAwesome5ProLight">&#xf108;</span> '
  else
    xrandr --output $m2 --left-of $m1
    echo -n '<span font="FontAwesome5ProLight">&#xf108;</span> '
    echo '<span font="FontAwesome5ProSolid">&#xf108;</span> '
  fi
elif [ "$numOfMonitors" -eq 1 ]; then
  echo '<span font="FontAwesome5ProSolid">&#xf108;</span> '
else
  notify-send "More than 2 monitors are not yet supported."
fi

