#!/usr/bin/env sh

# TODO: Implement a default action which leaves the layout as it is.
#       Read monitor positions from xrandr and set them via xrandr --output

monitors=$(xrandr | grep " connected" | awk '{ print $1 }')
numOfMonitors=$(echo "$monitors" | wc -l)
if [ "$numOfMonitors" -eq 2 ]; then
  # Get monitors' names
  m1=$(echo "$monitors" | head -n 1)
  m2=$(echo "$monitors" | tail -n 1)

  # LMouse: Primary to the left; to the right otherwise.
  if [ "$button" -eq 1 ]; then
    xrandr --output $m1 --left-of $m2
    echo -n '<span font="FontAwesome">&#xf108;</span> '
    echo '<span font="FontAwesome">&#xf108;</span> '
  else
    xrandr --output $m2 --left-of $m1
    echo -n '<span font="FontAwesome">&#xf108;</span> '
    echo '<span font="FontAwesome">&#xf108;</span> '
  fi
elif [ "$numOfMonitors" -eq 1 ]; then
  echo '<span font="FontAwesome">&#xf108;</span> '
else
  notify-send "More than 2 monitors are not yet supported."
fi

