#!/bin/zsh

if [ "$#" = "0" ]; then
  charging=$([ "$(acpi -b | awk -F'[, ]' '/^Battery/ { print $3 }')" = "Charging" ] \
    && echo 'true' \
    || echo 'false')

  charge=$(acpi -b | awk '/^Battery/ { print $4 }' | tr -d '%,' | xargs printf '%.3d')

  [ "$charging" = "true" ] \
    &&  echo -n '<span font="FontAwesome5ProLight">&#xf376;</span> ' \
    || echo -n '<span font="FontAwesome5ProLight">&#xf240;</span> '

  echo $charge

  pkill --signal SIGRTMIN+10 i3blocks
fi
