#!/usr/bin/env zsh

notify() {
	sudo -E -u stan notify-send "$@"
}


[[ "$DEVTYPE" != "disk" ]] && exit

#notify "$(env)"

if [ "$ACTION" = "add" ]; then
	notify "disk attached"
elif [ "$ACTION" = "remove" ]; then
	# Remove events don't provide busnum and devnum information.
	notify "disk removed"
fi
