#!/usr/bin/env sh

battery() {
  for p in /sys/class/power_supply/BAT?/capacity; do
    echo "$(cat "$p")%"
  done
}

power() {
  device=$(ls /sys/class/power_supply/ | grep -v 'BAT') # AC device names differ
  [ "$(cat /sys/class/power_supply/"$device"/online)" -eq 1 ] && printf ⚡|| printf 🔋

  for p in /sys/class/power_supply/BAT?/capacity; do
    echo " $(cat "$p")%"
  done
}

systime() {
  date '+%d. %B %H:%M:%S'
}

keymap() {
  echo "⌨ $(setxkbmap -query | grep layout | awk '{ print $2 }')"
}

backlight() {
  case $BUTTON in
    1) {
      if [ -f /tmp/redshift-on ]; then
        redshift -x
        rm /tmp/redshift-on
      else
        redshift -PO 2500K
        touch /tmp/redshift-on
      fi } > /dev/null
      ;;
    4) light -A 10 ;;
    5) light -U 10 ;;
  esac
  printf "☼ %.f" $(light)
}

ding() {
  [ ! -f /tmp/foo ] && echo 0 > /tmp/foo
  cat /tmp/foo
  echo $(( $(cat /tmp/foo) + 1 )) > /tmp/foo
  notify-send "Button = $BUTTON"
}

"$@" | tr -d '\n'
