#!/usr/bin/env sh

# Launch debugpy server and send F5 keypress to active window. Used to start a
# debug session in vscode from the terminal.
#
# This assumes that the currently selected debug configuration will attach to
# the server and can be launched by pressing the $KEY. Note that vscode
# ignores synthetic events, and thus the XTEST extention must be used (hence
# no '--window <WID>' options can be used with xdotool).
#
# Usage example: From the built-in vscode terminal run
#     vscpy ./mymodule.py arg1 arg2 --opt foo

HOST=localhost
PORT=5678
KEY=F5

(
	sleep 0.5s
	xdotool key $KEY # must use XTEST for vscode
)&
python3 -m debugpy --listen $HOST:$PORT --wait-for-client "$@"
