# Path to your oh-my-zsh installation.
export ZSH=$HOME'/.config/zsh/oh-my-zsh'
export ZSH_HOME=$HOME'/.config/zsh'
export ZSH_DISABLE_COMPFIX="true"
export ZSH_COMPDUMP=$ZSH_HOME/backup
export HISTFILE=$ZSH_HOME/backup
ZSH_THEME="robbyrussell"
COMPLETION_WAITING_DOTS="true"

plugins=(
  git wd colored-man-pages extract zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
[[ -r $ZSH_HOME/setup-specific.zsh ]] && source $ZSH_HOME/setup-specific.zh
source $ZSH_HOME/startup.zsh
source $ZSH_HOME/functions.zsh

# User configuration

export EDITOR='nvim'
export BROWSER='firefox'

alias xclip='xclip -selection clipboard'
alias vim=nvim
alias ls='ls --almost-all --color=tty'

export DISPLAY=localhost:0.0
export LS_COLORS="$(vivid generate molokai)"
